### ISSUE TITLE
no response

### ISSUE THREAD

**Issue by Gys** [theplant/bingtranslator#1]
I tried this with the example given (and my own credentials).
I get an empty result with no error.

Looking into the code I noticed this:
https://github.com/theplant/bingtranslator/blob/master/translator/translator.go#L55
The code does not test the Status of the resulting Response.
In my case this is 400. So it seems something is wrong or has changed in the API url ?

**Comment by Gys** [comment]
Got the message below after only trying this translator lib... Microsoft is very picky ?!

**We've got a little problem. Your subscription 'Free Trial{cbbfabc0-725d-400a-8090-c5afd5c62b04}' and services were disabled on Sun, 19 Apr 2015 11:10:15 GMT because we detected a violation of our service terms.**

Luckily I already switched to Google. Much better registration experience and easier api. Worked instantly. Its a payed service but it saved me time.

**Comment by athom** [comment]
hi @Gys , thanks for reporting.

I had tested the example and it works fine, to be clear, here I am talking the [main.go](https://github.com/theplant/bingtranslator/blob/master/main.go), not the code in README.

yes, I agree with you that  the 400 should be check in the response. 

AFAIK, there are 2 cases lead to the 400, incorrect secret and limited account. Seems you had the problem of the account issue.

**Comment by Gys** [comment]
I tried it all, including the main.go ;-)
Copied and pasted the secret so that would not have been the problem (even checked the first and last digits once).

Strange this happened. I registered with Azure especially for this api and only tried to use your code. 
I wanted to contact support to get more info on what exactly went wrong. However, the provided link leads nowhere. Looks like the only option is to put in on a forum but that seemed inadequate for my problem.

Glad I don't use the account (or Bing / Azure) otherwise.

**Comment by athom** [comment]
tried with my new registered free trial account

![](http://content.screencast.com/users/yeer/folders/Jing/media/e9d686c4-9d70-46e8-adc5-e7c153cceccf/00001289.png)

and it works.

```
➜  bingtranslator git:(master) go run main.go -i swordfish1234567 -s +rObkghoe/EM9l2jPBPVDdhx/y3BhG5JSPqtIt0244E=
Translate
[de: Mal sehen, wie Sie dies übersetzen.]
[de: <div class="stream-content-body markdown-style">
                    <p><span class="j-show-object-content" data-object-id="foo" data-org-id="bar">@<span>Name</span></span> Wie schwer wäre es das Suchsystem spuckte die hochwertigen Begriffe in ein Stück Text erweitern?</p>
                </div>]
[de: <li>Beginnen Sie einen Eintrag mit dem Schreiben<br></li> de: <li>Qortex ständig aktualisieren die "interessantesten" X-Worte, wie Sie schreiben<br></li>]
map[et:Estonian -- eesti ko:Korean -- 한국의 mt:Maltese -- Malti no:Norwegian -- norsk es:Spanish -- español it:Italian -- italiano tlh-qaak:Klingon (pIqaD) ru:Russian -- русский ar:Arabic -- العربية zh-cht:Chinese Traditional -- 繁體中文 en:English de:German -- Deutsch mww:Hmong Daw -- Hmong Daw sl:Slovenian -- slovenščina ur:Urdu -- اردو fi:Finnish -- suomalainen he:Hebrew -- עברית ro:Romanian -- român sv:Swedish -- Svenska tr:Turkish -- Türk el:Greek -- ελληνικά ja:Japanese -- 日本語 fa:Persian -- فارسی sk:Slovak -- slovenský uk:Ukrainian -- Український lv:Latvian -- Latvijas vi:Vietnamese -- Việt cs:Czech -- čeština da:Danish -- dansk nl:Dutch -- Nederlands hi:Hindi -- हिंदी tlh:Klingon pl:Polish -- polski pt:Portuguese -- português th:Thai -- ภาษาไทย bg:Bulgarian -- български ca:Catalan -- Català hu:Hungarian -- magyar id:Indonesian -- Indonesia lt:Lithuanian -- Lietuvos zh-chs:Chinese Simplified -- 简体中文 fr:French -- français ht:Haitian Creole -- kreyòl ayisyen ms:Malay -- Melayu]
```

I would like to support you, if you provide some more details and tech related information.

**Comment by Gys** [comment]
Thank you for the offer. But as I wrote already, I got my app working with Google Translate effortlessly. I am busy as it is and lost already to much time with the Bing thing. I probably did something embarrassing stupid ;-)
